import type { RawNetwork, RawScript, RawInputAccess, DomSignals, FrameworkSignals, Attribution } from '../engine/types';

/**
 * v1.1 transport: a per-page nonce names a CustomEvent channel on `document`.
 * This replaces `window.postMessage(m, '*')`, which leaked Archify's observations
 * to any page `message` listener and accepted spoofed messages. The nonce is
 * generated by the content script and handed to the MAIN-world injected script
 * via a transient attribute it reads-and-removes immediately. A page script can
 * neither read this channel nor forge messages on it without guessing the nonce.
 */
export const CHANNEL_ATTR = 'data-archify-channel';

export function channelName(nonce: string): string {
  return `archify:${nonce}`;
}

export interface HoverPayload {
  dom: DomSignals;
  framework: FrameworkSignals;
  componentName: string | null;
  x: number;
  y: number;
}

export type InjectedMessage =
  | { kind: 'network'; payload: RawNetwork & { attribution: Attribution | null } }
  | { kind: 'script'; payload: RawScript }
  | { kind: 'inputAccess'; payload: RawInputAccess }
  | { kind: 'hover'; payload: HoverPayload }
  | { kind: 'pageGlobals'; payload: { globals: string[] } }
  | { kind: 'interaction'; payload: { id: number; component: string | null; dom: DomSignals } }
  | { kind: 'storage'; payload: { area: 'local' | 'session' | 'cookie'; key: string; attribution: Attribution | null } }
  | { kind: 'nav'; payload: { to: string; kind: 'push' | 'replace' | 'pop'; attribution: Attribution | null } };

export function isInjectedMessage(d: unknown): d is InjectedMessage {
  return !!d && typeof d === 'object' && typeof (d as { kind?: unknown }).kind === 'string';
}
